### ISSUE TITLE
Is it possible to add DCP-7055 support?

### ISSUE THREAD

**Issue by queeup** [pdewacht/brlaser#1]
I want to know if it's possible to add DCP-7055 support. If it's possible, what do you need to know about this printer?

**Comment by queeup** [comment]
Here it is: http://pastebin.com/HdHUCRm1

No idea about scanner. I just using Brother scanner drivers on my Linux.

**Comment by DamirPorobic** [comment]
I've installed the x86 brother printer driver on the Raspberry Pi using QEMU emulation and that works fine. The scanner driver is installed to but SANE is unable to open the shared libraries...

**Comment by gpolitis** [comment]
I've compiled and installed the brlaser driver on a Raspberry Pi and the printer works just fine. I'm even able to print with my iPhone using AirPrint. Should we close this issue?

**Comment by timofonic** [comment]
@queeup @pdewacht @DamirPorobic @gpolitis Any news about this? What's the current status of this issue?

**Comment by pdewacht** [comment]
DCP-7055's seem to work fine. This issue has gotten pretty chatty, if there's something that still needs to be dealt with, please open a new issue.
