### ISSUE TITLE
Make fails on FreeBSD

### ISSUE THREAD

**Issue by jd1** [pdewacht/brlaser#10]
I tried to use this drivers with FreeBSD. This is what I did:

./autogen.sh
./configure
make

But make fails with the following error:

```
make  all-am
  CXXLD    src/rastertobrlaser
src/main.o: In function `main':
/usr/home/jo/brlaser/src/main.cc:68: undefined reference to `libiconv_open'
/usr/home/jo/brlaser/src/main.cc:78: undefined reference to `libiconv'
/usr/home/jo/brlaser/src/main.cc:84: undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
*** Error code 1

Stop.
make[1]: stopped in /usr/home/jo/brlaser
*** Error code 1
```

**Comment by colddiver** [comment]
I managed to fix those on FreeNAS (FreeBSD jail). See here:
https://github.com/colddiver/brlaser

Everything works now (even airprint through cups).

**Comment by jd1** [comment]
@colddiver Thanks. I have to set LIBS = -liconv, but then it works!

**Comment by colddiver** [comment]
If you want to setup AirPrint, I just finished documenting the process [here](https://www.colddiver.com/cups-and-airprint-with-brother-dcp-7030-dcp-7055-and-dcp-7065dn-on-freebsd-freenas-and-possibly-raspberry-pi/)...

**Comment by timofonic** [comment]
@pdewacht @jd1 @colddiver Has this issue been fixed? If yes, whi is this issue still open?

Can anyone reply? Any news? Anyone there?

**Comment by pdewacht** [comment]
brlaser no longer uses iconv, so this issue should be gone now.
