### ISSUE TITLE
HL-1110 DPI only printing certain PDF at 300DPI

### ISSUE THREAD

**Issue by buleherb** [pdewacht/brlaser#111]
Ubuntu 20.04.2 LTS and CUPS 2.3.1 on a Raspberry Pi 4B 4GB. Driver installed a week ago.

I have 2 versions of a PDF - [one with a single copy of a certain layer](https://imgur.com/guhlzi2) and [one with a duplicate of this layer on the same page](https://imgur.com/EpOVIMb). 

Using this driver (with CUPS) at 600DPI and 1200DPI, the second PDF (with the duplicate layer) doesn't print (it does wake the printer from sleep though). At 300DPI it prints. Directly connecting the printer to a Macbook Pro, both PDFs print at 300/600/1200DPI.

Attached log file below contains everything from the beginning of the job entry (Job 213) to the completion and unloading of it for the second (not-working PDF), CUPS settings set to 600DPI. From the debug logs (level 1) below, CUPS doesn't seem to report any problems, neither does brlaser although I may be missing something. According to CUPS the job seems to go through and print fine.

[CUPS-error_log.txt](https://github.com/pdewacht/brlaser/files/5934719/CUPS-error_log.txt)

**Comment by tonivj5** [comment]
Hey @buleherb, have you tried to compile brlaser from master? It worked to me 👍🏻 

Check this issue for more info https://github.com/pdewacht/brlaser/issues/52

**Comment by buleherb** [comment]
@tonivj5 I'll try today, thanks for letting me know

**Comment by buleherb** [comment]
@tonivj5 this worked great, issue solved. I didn't test the HL-L2300D as much as the HL-1110, but of the 25 printers I have here these two seemed to not print that one PDF. I was going to fix the HL-1110 and then look at the L2300D - both are working perfectly now after compiling brlaser from master. Thank you very much for this
