### ISSUE TITLE
Brother HL-1200 series not showing option for brlaser in cups admin

### ISSUE THREAD

**Issue by thanksmister** [pdewacht/brlaser#116]
Brother HL-1200 series says it's supported with brlaser, but there is no brlaser option for HL-1200 in the cups admin.  I was able to get some printing support using the Brother DCP-1510 series and Brother HL-L2300D but not all documents print.

Output:

```
Device: uri = usb://Brother/HL-1200%20series?serial=H0N702650
        class = direct
        info = Brother HL-1200 series
        make-and-model = Brother HL-1200 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-1200 series;CLS:PRINTER;CID:Brother Laser Type3;
        location = 
```

<img width="919" alt="Screen Shot 2021-03-23 at 9 15 29 AM" src="https://user-images.githubusercontent.com/142340/112145117-bc0acd80-8bb8-11eb-9ceb-8d012837f7a5.png">

**Comment by QORTEC** [comment]
Looking at your screenshot it looks like you currently have brlaser v4 installed, and support for the Brother HL-1200 series printer was added in brlaser v5.

brlaser release v4 [`d80491b`](https://github.com/pdewacht/brlaser/tree/d80491b1054ade5612a5a8617c5936044018bae7)
brlaser release v5 [`ff68db0`](https://github.com/pdewacht/brlaser/tree/ff68db0f93d3e2f5704f42b5580f3c2272122d12)

**Comment by thanksmister** [comment]
OK, I tried to update by installing it again and it says its already the newest version?

```
sudo apt-get install -y printer-driver-brlaser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
printer-driver-brlaser is already the newest version (4-1).
```

So do I have to make brlaser from the repository?  The documentation says it's already installed, which is a Raspberry PI running Raspian.  Is there a way to update it?

**Comment by thanksmister** [comment]
I was able to update brlaser with this tutorial https://www.raspberrypi.org/forums/viewtopic.php?t=252591 and resolved the issue.  I now have the latest version of brlaser and the Brother HL-1200 brlaser driver appears.  Thanks, closing the issue.

<img width="928" alt="Screen Shot 2021-03-26 at 12 24 58 PM" src="https://user-images.githubusercontent.com/142340/112654704-6d666900-8e2e-11eb-8328-e1a2485ccacd.png">
