### ISSUE TITLE
Unlisted ghostscript dependency

### ISSUE THREAD

**Issue by dcousens** [pdewacht/brlaser#13]
At least,  for me it was required for this to work.   Otherwise all I get from CUPS is:

> Can't read raster data

Using a **Brother HL-L2300D series**

**Comment by timofonic** [comment]
@pdewacht @hollobon Any news about this?

**Comment by drahnr** [comment]
This is already fixed in my repo

**Comment by pdewacht** [comment]
This really isn't an issue with brlaser (brlaser doesn't use Ghostscript in any way), but with the way cups-filters is packaged in some distros (e.g. Arch Linux).

- The distro's packaging system allows installation of cups-filters without ghostscript, but
- cups-filters assumes Ghostscript is always present and fails silently if it's not.

The result is that vague "Can't read raster data" error message.

In cups-filters 1.18.0 proper error handling was added in case Ghostscript is missing.

**Comment by dcousens** [comment]
Thanks for the clarification @pdewacht
