### ISSUE TITLE
Brother HL-L2300D only prints first page of PDF

### ISSUE THREAD

**Issue by zakhikhan** [pdewacht/brlaser#132]
I am using the brlaser 4.0 driver with CUPS 2.2.10 on a raspberry pi running Raspberry Pi OS. When I print from the local machine using the lp command, only the first page of a PDF document prints. However, when I go to the completed jobs log, it lists the file as having 10 pages and the print as having been completed.

I used the same printer on Windows with the Brother driver and the issue did not occur. 

Please let me know if you would like any further info.

**Comment by zeroheure** [comment]
Could you try with latest release (brlaser version 6) ?

**Comment by zakhikhan** [comment]
I installed version 6, and now it works fine and can print multiple page PDF documents correctly.
