### ISSUE TITLE
Could  support the 2240 series??Thanks very much!

### ISSUE THREAD

**Issue by EPTansuo** [pdewacht/brlaser#136]
device：  uri = usb://Brother/HL-2240%20series?serial=B4J415392
        class = direct
        info = Brother HL-2240 series
        make-and-model = Brother HL-2240 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-2240 series;CLS:PRINTER;CID:Brother Laser Type1;
        location =

**Comment by zeroheure** [comment]
Should already works. Did you try with latest version ?

**Comment by sebastiansam55** [comment]
Adding on to this, they literally mean select anything in the CUPS web interface that says "brlaser" after installing the package, works for me with an hl2240 and a rpi0w

**Comment by EPTansuo** [comment]
> @EPTansuo can you confirm that your printer works with the driver? You can check by just selecting any entry marked 'brlaser'.

I tested it, and it works very well. Thanks very much for your contribution!
