### ISSUE TITLE
Duplex Support

### ISSUE THREAD

**Issue by instantandrew** [pdewacht/brlaser#14]
I've been able to use this to make my Raspberry Pi Zero W work as a wireless print server for my Brother DCP-7060D. Thanks! It might be worth marking this device as supported.

However, there is no Duplex support when using AirPrint. I notice you're working on it - I tried your test duplex code and that didn't seem to work for me (blank pages printed out). Is this still in the works?

**Comment by instantandrew** [comment]
Ah, never mind - the forked version written by drahnr works for DCP-7060D and provides working duplex support for AirPrint.

**Comment by archenemies** [comment]
Why is this closed? Surely if [drahnr's version](https://github.com/drahnr/brlaser) fixes the problem, then his fixes should be incorporated into the main project?

I was using package "printer-driver-brlaser" on Raspbian to interface to a Brother_DCP-7065DN; I found that Duplex was broken with the main package; but manually installing drahnr's version fixed the problem for me, and now I can print duplex.

**Comment by archenemies** [comment]
Never mind it looks like duplex is fixed in this version and the Raspbian package is just behind.

Umm... thank you for the excellent software!
