### ISSUE TITLE
New Printer Brother HL-5170DN

### ISSUE THREAD

**Issue by chsymann** [pdewacht/brlaser#167]
`sudo lpinfo --include-schemes usb -l -v`

outputs

```
Device: uri = usb://Brother/HL-5170DN%20series?serial=D5J807428
        class = direct
        info = Brother HL-5170DN series
        make-and-model = Brother HL-5170DN series
        device-id = MFG:Brother;CMD:PJL,PCL,PCLXL,POSTSCRIPT;MDL:HL-5170DN series;CLS:PRINTER;
        location = 
```

**Comment by QORTEC** [comment]
Hi @chsymann can you please confirm that you've tested the driver and it works?
I'll add your printer to my pull request the next time I get around to updating it.

**Comment by chsymann** [comment]
nevermind, I think it didn't work in the end, unfortunately.
In the meantime, I got rid of the printer and switched to something new....
