### ISSUE TITLE
Unfork the @drahnr fork that adds RPM capabilities and maybe more?

### ISSUE THREAD

**Issue by timofonic** [pdewacht/brlaser#18]
Hello.

What about unforking the @drahnr [brlaser fork](/drahnr/brlaser) that adds RPM capabilities and maybe more too?

@pdewacht @Photon89 @hollobon @lnussel @cinemast @xc-racer99 @rkreis @jd1 @colddiver @queeup @DamirPorobic @gpolitis @dcousens @drahnr @mabrowning @schuttes @vanabel @igraltist  Any news about this? Anyone still interested in this project?

Kind regards.

**Comment by lnussel** [comment]
Not sure why I'm pinged here but since I maintain the package in openSUSE I can say the rpm bits there add no value from a distribution's PoV.

**Comment by pdewacht** [comment]
Yeah, as far as I know no distro wants to see rpm/deb/etc bits in an upstream repo.
I went through the forks not too long ago and merged everything that seemed interesting.
