### ISSUE TITLE
My Brother HL-L2320D prints text documents fine with the driver but photos seem to never print

### ISSUE THREAD

**Issue by adam-jones-net** [pdewacht/brlaser#186]
As the subject says really.  In cups, it has a status of success and it seems to think that the job printed just as successfully as a text file, however the photo jobs never appear.

The printer for a few seconds starts to flash the _Ready_ green light, then it goes back to a dimmer constant green ready and nothing appears.

Anyone got any troubleshooting ideas ?   My clients are all Windows 11 PCs.

**Comment by QORTEC** [comment]
For debugging try to set the printer to `300 ppi`. I don't know the reason but sometimes higher ppi jobs get cut short or just fail outright.

Also your wording suggests you have a cups server, if you could include any details/specs maybe helpful.

Lastly if you have time, trying to print with a Linux/FreeBSD client may also help in tracking down this bug. 
_e.g._ Is an issue specific to windows or does it effect all OSs?

**Comment by adam-jones-net** [comment]
I've managed to fix by installing 2.4.x on my Raspberry Pi.  At the time of writing, 2.4.x isn't actually available in the packages available to Pi OS, so I actually setup a new sdcard with Armbian on it, and it's packages are much more up to date and apt-get install cups instantly resulted in me with 2.4.1 installed.  So at last a fix!

**Comment by trobriander** [comment]
@adam-jones-net I have Cups 2.4.2 installed but I have exactly the same printer as you and exactly the same problem. Did you do anything special to get it to work?

**Comment by adam-jones-net** [comment]
Hi no really getting onto 2.4 was the big thing for me. The printer then became automatically discoverable on the LAN and it installed with no prompts for drivers. I have no custom brother drivers installed on windows. I'd deleted all that before going through the add new printer routine. 

> @adam-jones-net I have Cups 2.4.2 installed but I have exactly the same printer as you and exactly the same problem. Did you do anything special to get it to work?
