### ISSUE TITLE
Brother DCP-7065DN duplex printing

### ISSUE THREAD

**Issue by kecinzer** [pdewacht/brlaser#20]
Recently I installed latest Raspbian on my RPI and configured my printer Brother DCP-7065DN. But I'm not able to set up duplex printing for it. I can see this on my CUPS administration:

Description: | Brother DCP-7065DN
Brother DCP-7065DN, using brlaser v3 (grayscale)
lpd://192.168.0.150/BINARY_P1
job-sheets=none, none media=iso_a4_210x297mm sides=one-sided

When I printing to this printer from iOS or macOS I can't set two sided (duplex) printing.
Is there anything more that I need to do for duplex printing?

**Comment by pdewacht** [comment]
The last released version didn't support duplex printing yet. It will be in the next release.
You can build from git if you need it now.
