### ISSUE TITLE
Brother MFC-7240 Printer Works

### ISSUE THREAD

**Issue by Biddlebaddleboo** [pdewacht/brlaser#21]
Just to let you know, the Brother MFC-7240 printer works with the MFC-7360N driver.

**Comment by pdewacht** [comment]
Thanks! Can you give the output of this command?
 
    sudo lpinfo --include-schemes usb -l -v

This will include the IEEE-1284 Device ID, which is used for plug-and-play driver installation.

**Comment by Biddlebaddleboo** [comment]
root@DietPi:~# lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/MFC-7240?serial=U63314K3J514219
        class = direct
        info = Brother MFC-7240
        make-and-model = Brother MFC-7240
        device-id = MFG:Brother;MFG:Brother;CMD:PJL,HBP;MDL:MFC-7240;CLS:PRINTER;CID:Brother Laser Type1;
        location =

**Comment by pdewacht** [comment]
Thanks!
