### ISSUE TITLE
HL-L2360DW

### ISSUE THREAD

**Issue by Owesome** [pdewacht/brlaser#22]
Device: uri = usb://Brother/HL-L2360D%20series?serial=U63883G5N939629
        class = direct
        info = Brother HL-L2360D series
        make-and-model = Brother HL-L2360D series
        device-id = MFG:Brother;CMD:PJL,PCL,PCLXL,URF;MDL:HL-L2360D series;CLS:PRINTER;CID:Brother Laser Type1;URF:W8,CP1,IS4-1,MT1-3-4-5-8,OB10,PQ4,RS300-600,V1.3,DM1;
        location =

**Comment by pdewacht** [comment]
Thanks! I've added that printer.
