### ISSUE TITLE
DCP-7080 also works!

### ISSUE THREAD

**Issue by zidan1128** [pdewacht/brlaser#24]
Dear sir,
I have tired brlaser v4 for my Brother DCP-7080 printer on raspberry pi 3b, I choose the model as DCP-7055, it works well. Thank you so much for your work!
btw, DCP-7080 is a special model in Asia area.
Best regards,
Z

Device info:
Device: uri = usb://Brother/DCP-7080?serial=E70207G7J000000
        class = direct
        info = Brother DCP-7080
        make-and-model = Brother DCP-7080
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:DCP-7080;CLS:PRINTER;CID:Brother Laser Type1;
        location =

**Comment by pdewacht** [comment]
Thanks, added!

**Comment by CaoKang-David** [comment]
I have a dcp7080D printer, I want to make it work on raspbian OS with raspberry pi 4 model B. 
I installed the brlaser v6 drivers, and it can print documents with text only, but it cannot print pictures.
anyone help？
