### ISSUE TITLE
HL-L2320D works too

### ISSUE THREAD

**Issue by writerbenjamin** [pdewacht/brlaser#25]
Below is output of sudo lpinfo --include-schemes usb -l -v:

brittger@pallas:~ $ sudo lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/HL-L2320D%20series?serial=U63877M4N610239
        class = direct
        info = Brother HL-L2320D series
        make-and-model = Brother HL-L2320D series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-L2320D series;CLS:PRINTER;CID:Brother Laser Type1;
        location =

**Comment by pdewacht** [comment]
Thanks, added!

People have reported all kinds of odd problems with the HL-L2300D (see #4). For example, people seem to have trouble printing this file: https://static.googleusercontent.com/media/www.google.com/en//landing/cloudprint/testpage.pdf
Do you see that kind of thing with your printer?

**Comment by writerbenjamin** [comment]
I cannot print the above file.  However, text files work fine.  I primarily use this for printing long word documents.  I can print the CUPS test page though.

**Comment by al3x-huang** [comment]
I can print the above file just fine on the HL-L2320D. Compiled the latest version on Raspberry Pi running CUPS. Will report back if anything changes.

**Comment by al3x-huang** [comment]
Sorry for bringing up an old issue but I've been using this printer for a while now and there are definitely pages similar to the one mentioned (testpage.pdf) that I cannot print although I CAN print testpage.pdf. I took a look at #4 and realized that people were having the same issue. I think it's interesting that with the same driver and printer setup testpage.pdf works for me but not for others. Maybe there's a way to use this case as a test to isolate the core problem? I'm not familiar with how CUPS handles print data but if someone can point me in the right direction perhaps I can try to post it here so everyone can try it and maybe spot the potential issue?

**Comment by pioelad** [comment]
I am also able to confirm that v5 fixes the issues mentioned above and I was even able to print the testpage.pdf file having no issues. (I am using Raspbian and have tried to print from a windows PC, a MacOS laptop and an iOS device).
