### ISSUE TITLE
Brother HL-1202R works with this driver

### ISSUE THREAD

**Issue by RussianNeuroMancer** [pdewacht/brlaser#27]
Hi

Brother HL-1202R works with yours driver. Thanks for brlaser project :)

Device: uri = usb://Brother/HL-1200%20series?serial=M7N411923
        class = direct
        info = Brother HL-1200 series
        make-and-model = Brother HL-1200 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-1200 series;CLS:PRINTER;CID:Brother Laser Type3;
        location =

**Comment by pdewacht** [comment]
Thanks, added!
