### ISSUE TITLE
How to install it on raspiberry pi?

### ISSUE THREAD

**Issue by vanabel** [pdewacht/brlaser#3]
I know your driver from stackexchange, but it seems you don't mention how to install it, could your explain it a bit?

**Comment by igraltist** [comment]
./autogen.sh
./configure
make 
make install
I install it on my cubietruck and this is an arm machine and its work fine. In cups e.g. choose brlaser.

**Comment by schuttes** [comment]
I've tried to use this driver with a Raspi b and Raspian Wheezy (and Jessie) for a Brother HL 2300D. The installation process is documented here: http://craighoad.com/blog/installing-brother-hl-l2300d-in-raspbian-jessie-made-easy/

The problem: I get this error message when trying to print a test page "Can't read raster data". The compilation works flawlessly, so libraries and headers should all be there. The error message seems to be thrown when cupsRasterOpen() fails. Could anybody please tell me how to further troubleshoot/solve this problem? Cups log files don't give more info. Thanks so much!

**Comment by dcousens** [comment]
@schuttes you need `ghostscript` installed

**Comment by timofonic** [comment]
@pdewacht @Photon89 @hollobon @lnussel @cinemast @xc-racer99 @rkreis @jd1 @colddiver @queeup @DamirPorobic @gpolitis @dcousens @drahnr @mabrowning @schuttes @vanabel @igraltist  Any news about this? Anyone still interested in this project?
