### ISSUE TITLE
Brother HL-5030; print issues

### ISSUE THREAD

**Issue by RopoMen** [pdewacht/brlaser#33]
Hi,

Here is informations for Brother HL-5030, printer started working after I added HL-5030 informations in to `brlaser.drv.in` file and build the driver.

```
pi@raspberrypi:/tmp/brlaser $ sudo lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/HL-5030%20series?serial=B3J200238
        class = direct
        info = Brother HL-5030 series
        make-and-model = Brother HL-5030 series
        device-id = MFG:Brother;CMD:PJL,PCL;MDL:HL-5030 series;CLS:PRINTER;
        location = 

{
  ModelName "HL-5030"
  Attribute "NickName" "" "Brother HL-5030 series, $USING"
  Attribute "1284DeviceID" "" "MFG:Brother;CMD:PJL,PCL;MDL:HL-5030 series;CLS:PRINTER;"
  PCFileName "hl5030.ppd"
}
```

Thank you!!

**Comment by pdewacht** [comment]
Sorry, I missed you report. I've heard of some other printers with similar problems, in #36 the HL-2140 and HL-2270DW are mentioned. Unfortunately, I can't help, somebody with access to one of these printers will have to debug this.

**Comment by pdewacht** [comment]
Fixed in version 6.
