### ISSUE TITLE
Brother DCP-L2500D works

### ISSUE THREAD

**Issue by jkwakman** [pdewacht/brlaser#35]
Dear mr de Wacht,
Thank you for you're awesome work! I've got my printer Brother DCP-L2500D working with you're driver (brlaser v3 (grayscale)). Below the output from the lpinfo:

Device: uri = usb://Brother/DCP-L2500D%20series?serial=E73908C6N326411
        class = direct
        info = Brother DCP-L2500D series
        make-and-model = Brother DCP-L2500D series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:DCP-L2500D series;CLS:PRINTER;CID:Brother Laser Type1;
        location =

**Comment by jkwakman** [comment]
https://static.googleusercontent.com/media/www.google.com/en//landing/cloudprint/testpage.pdf

Test page for cloudprint also works!

**Comment by tmn505** [comment]
Hi.
When You tested the printer with brlaser, did the 1200dpi work? If yes, what firmware version does Your printer have?
