### ISSUE TITLE
Brother HL-L2340D

### ISSUE THREAD

**Issue by bigrobinson** [pdewacht/brlaser#37]
sudo lpinfo --include-schemes usb -l -v: produced no ouput
print successful

**Comment by DMSwan** [comment]
I used the 2320D print driver. I can duplex print, and I'm able to share the printer with a Windows 10 and a Mac computer on my local network via the CUPS server.

sudo lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/HL-L2340D%20series?serial=U63879E4N142850
        class = direct
        info = Brother HL-L2340D series
        make-and-model = Brother HL-L2340D series
        device-id = MFG:Brother;CMD:PJL,HBP,URF;MDL:HL-L2340D series;CLS:PRINTER;CID:Brother Laser Type1;URF:W8,CP1,IS4-1,MT1-3-4-5-8,OB10,PQ4,RS300-600,V1.3,DM1;
        location =
