### ISSUE TITLE
Brother HL-1202R refuse to print certain documents

### ISSUE THREAD

**Issue by RussianNeuroMancer** [pdewacht/brlaser#38]
Hello!

I find that Brother HL-1202R refuse to print certain pdf files. Previous, all pdf files that can not be printed was private, so I couldn't share it here. However, this time there is public pdf file that can not be printed on  Brother HL-1202R if we print via brlaser.

Sample: https://yadi.sk/i/yNeNhucTjx1OXg
CUPS debug log: https://paste.fedoraproject.org/paste/Hr0vKly57SfIY7FmUpzdyQ

**Comment by pdewacht** [comment]
Hi! Could you try to print those files again with the current git version? I think this bug might have been fixed.

**Comment by RussianNeuroMancer** [comment]
@pdewacht ok, I will try to build driver, but currently I can't promise when I will be able to do so.

**Comment by RussianNeuroMancer** [comment]
I find that when brlaser from master is installed on fresh Ubuntu installation, CUPS add and configure HL-1202R automatically. @pdewacht thank you for adding this printer to list of supported printers! :)

I also can confirm that all three documents mentioned above now print without issues on HL-1202R, @onnokort thank you for fixing this.
