### ISSUE TITLE
Brother HL-2140; print issues

### ISSUE THREAD

**Issue by aep** [pdewacht/brlaser#39]
```
$ lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/HL-2140%20series?serial=A9J283210
        class = direct
        info = Brother HL-2140 series
        make-and-model = Brother HL-2140 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-2140 series;CLS:PRINTER;
        location = 
```

printing works with very poor quality. there's bits missing.
![IMG_20190314_121935](https://user-images.githubusercontent.com/136926/54353113-8c34a100-4653-11e9-9741-f8617a61acd7.jpg)

**Comment by pdewacht** [comment]
I haven't seen those symptoms before. But could you try the current git? Somebody just contributed a fix for a problem with the HL-1210W, and who knows, it might fix this as well.

**Comment by tlnagy** [comment]
I can reproduce this on master using a Brother HL-2270DW. 

```
$ lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/HL-2270DW%20series?serial=G2N798770
        class = direct
        info = Brother HL-2270DW series
        make-and-model = Brother HL-2270DW series
        device-id = MFG:Brother;CMD:PJL,PCL,PCLXL;MDL:HL-2270DW series;CLS:PRINTER;
        location =
```

**Comment by pdewacht** [comment]
This is a guess, but could you try commit 7ed0d6f2e8d5a8192c5621898b3ff920c95b66dc? That was a change that I ended up reverting because it didn't seem to help anyone and it hurt compression ratios. But I think it might fix this problem.

**Comment by QORTEC** [comment]
@pdewacht I can confirm that the commit 7ed0d6f2e8d5a8192c5621898b3ff920c95b66dc works on my printer.
````
Device: uri = usb://Brother/HL-2270DW%20series?serial=#########
        class = direct
        info = Brother HL-2270DW series
        make-and-model = Brother HL-2270DW series
        device-id = MFG:Brother;CMD:PJL,PCL,PCLXL;MDL:HL-2270DW series;CLS:PRINTER;CID:Brother Laser Type1;
        location = 
````

Steps taken:
- use solbuild to build and install the drivers using commit ff68db0f93d3e2f5704f42b5580f3c2272122d12 (brlaser release v5)
- test page has the same artifacting issue as pictured above.
- use solbuild to build and install the drivers using commit 7ed0d6f2e8d5a8192c5621898b3ff920c95b66dc (suggested above)
- test page prints correctly (both tests done in "duplex" mode)

Printer Settings:
Device URI: ipp://1.1.1.1:631/ipp
Make and Mode: Brother HL-L2300D series, using brlaser v5
Toner Save Mode: enabled
2-Sided Printing: Longe-Edge (Portrait)

**Comment by pdewacht** [comment]
Fixed in version 6.

@QORTEC The HL-3170CDW supports AirPrint, that printer should work without drivers ("CUPS driverless printing").
