### ISSUE TITLE
Brother HL-2220 Series

### ISSUE THREAD

**Issue by grounded042** [pdewacht/brlaser#44]
I got this working with my Brother HL-2220 series printer. It does seem to have the same problem that #39 has, and I'll try the solution there.
```
Device: uri = usb://Brother/HL-2220%20series?serial=M0N113163
        class = direct
        info = Brother HL-2220 series
        make-and-model = Brother HL-2220 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-2220 series;CLS:PRINTER;
        location =
```

**Comment by grounded042** [comment]
I can confirm that using 7ed0d6f2e8d5a8192c5621898b3ff920c95b66dc from #39 works for me.

**Comment by pdewacht** [comment]
Fixed in version 6.
