### ISSUE TITLE
HL-2030 Series confirmed to work.

### ISSUE THREAD

**Issue by phyden** [pdewacht/brlaser#46]
Thanks so much for this!

On my Brother HL-2030 I had the same artifactural printing experience with the release v5 as reported by #44 and #39 which were fixed by using  7ed0d6f2e8d5a8192c5621898b3ff920c95b66dc instead.

```
Device: uri = usb://Brother/HL-2030%20series?serial=F8J920992
        class = direct
        info = Brother HL-2030 series
        make-and-model = Brother HL-2030 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-2030 series;CLS:PRINTER;
        location =
```

**Comment by pdewacht** [comment]
Thanks! Can you test again with the master branch? If that works, I'll release v6 tonight.

**Comment by phyden** [comment]
Just tested it with the current master branch. It's working nicely with my printer.
