### ISSUE TITLE
Brother HL-L2300D not available

### ISSUE THREAD

**Issue by bobblkabb** [pdewacht/brlaser#51]
Need advice.
Installed printer-driver-brlaser via yast (opensuse leap 15.1) but 2300 driver still missing. Only a few are listed when I search for 'brlaser'.

**sudo lpinfo --include-schemes usb -l -v** output:
```
Device: uri = usb://Brother/HL-L2300D%20series?serial=E73860C7N506806
        class = direct
        info = Brother HL-L2300D series
        make-and-model = Brother HL-L2300D series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-L2300D series;CLS:PRINTER;CID:Brother Laser Type1;
        location = 
```
What can I do?

![Screenshot_20191016_182300](https://user-images.githubusercontent.com/7815101/66938772-1ad22c00-f042-11e9-84dd-e1e71afc3883.png)

**Comment by pdewacht** [comment]
Looks like SUSE is shipping a version that's a few years old. Support for the HL-L2300D &co was only introduced recently, in version 5. Try compiling brlaser from source. Or perhaps try getting them to update their package; I'm not familiar with SUSE's procedures.
