### ISSUE TITLE
Brother HL-2380DW

### ISSUE THREAD

**Issue by gregf** [pdewacht/brlaser#54]
Would be nice if this one was working as well. Has anyone found a driver that works for it? I'm not using usb, doing wireless.

**Comment by pdewacht** [comment]
Hi gregf,
That printer supports Airprint, so it ought to work out of the box, without drivers, if your CUPS installation is ready for that.
Or else you can use this driver and just pick a printer with similar features (e.g. the HL-L2360DW).

**Comment by gregf** [comment]
OK Thank you
