### ISSUE TITLE
HL-L2375DW Works

### ISSUE THREAD

**Issue by leeb-dev** [pdewacht/brlaser#56]
brlaser 6, OpenBSD 6.6
Seems to be fine - duplex, multiple pages per side all good.

Device: uri = lpd://BRN3C2AF46E25E9/BINARY_P1
        class = network
        info = Brother HL-L2375DW series
        make-and-model = Brother HL-L2375DW series
        device-id = MFG:Brother;CMD:PJL,PCL,PCLXL,URF;MDL:HL-L2375DW series;CLS:PRINTER;CID:Brother Laser Type1;URF:W8,CP1,IS4-1,MT1-3-4-5-8,OB10,PQ3-4-5,RS300-600-1200,V1.4,DM1;
        location = 

Thanks!

**Comment by pdewacht** [comment]
Thanks, I'll add this in the next release.
