### ISSUE TITLE
Compile errors w/rt/ Raster.h "header not found" on Rpi4/Manjaro

### ISSUE THREAD

**Issue by TheRoarkster** [pdewacht/brlaser#59]
Hoping to get some guidance on an error I receive when trying to `cmake .` the package on a Raspberry Pi 4 running Manjaro with (almost) all of the necessary CUPS packages installed.

Essentially, when the package guilder gets to the point of `Looking for C++ include cups/raster.h`, it throws an error:
```
<cups/raster.h> header not found.  Are the CUPS development packages
  installed?
```
Comparing the [Debian](https://packages.debian.org/buster/arm64/libcups2-dev/filelist) and [Arch](https://www.archlinux.org/packages/extra/x86_64/libcups/files/) package lists for `libcups2-dev`, the only files **not included in the latter** (and also not on my Rpi4 machine) are:
```
/usr/lib/aarch64-linux-gnu/libcups.a
/usr/lib/aarch64-linux-gnu/libcups.so
/usr/include/cups/i18n.h
```
Notably, `/usr/include/cups/raster.h` is included in the Arch build and on my machine.

Any idea if these files are the issue or something else is at play?

**Comment by pdewacht** [comment]
Unfortunately I've never before heard of Manjaro. I'm afraid this is a bit beyond the scope of what I can give support for.

I see that it's a distribution based on Arch, and I know that Arch has an up-to-date brlaser package. Perhaps there's a way to install Arch packages on Manjaro?

Anyway, really the only thing that test does, is to try to compile a trivial C++ program that includes the header file:

    #include <cups/raster.h>
    int main() {
      return 0;
    }

If that fails, it indicates that there's something wrong with your compiler or with your CUPS installation. You can find the full error message from CMake's test in a file called `CMakeFiles/CMakeError.log` in the build directory.
