### ISSUE TITLE
Brother QL-500 works

### ISSUE THREAD

**Issue by attributeerror** [pdewacht/brlaser#60]
Brother QL-500 seems to be working fine as well :) 

`sudo lpinfo --include-schemes usb -l -v` output:
```
Device: uri = usb://Brother/QL-500?serial=G4Z791159
  class = direct
  info = Brother QL-500
  make-and-model = Brother QL-500
  device-id = MFG:Brother:CMD:PT-CBP;MDL:QL-500;CLS:PRINTER;
  location = 
```

**Comment by pdewacht** [comment]
Hi! This seems to be a label printer? Are you certain CUPS is not using [the ptouch driver](https://github.com/philpem/printer-driver-ptouch)? It lists your printer as supported, and it's shipped by most Linux distributions.
