### ISSUE TITLE
HL-2280DW works

### ISSUE THREAD

**Issue by nicocesar** [pdewacht/brlaser#61]
I used HL-2270DW and worked fine. It seems that the LCD screen and some other cosmetic things are the only difference between the models

used socket://[printer_ip_address]:9200 as URI 

BTW  `sudo lpinfo --include-schemes usb -l -v `  is returning nothing (this  is a network printer. let me know what information I can provide)

Thanks for this project

**Comment by pdewacht** [comment]
Glad to hear you got your printer working. Don't worry about the lpinfo output, somebody else already provided that.
