### ISSUE TITLE
Failed to print pdf file in landscape format

### ISSUE THREAD

**Issue by reinhard66-ubuntu** [pdewacht/brlaser#67]
With your brlaser driver i am unable to print this pdf file in the landscape format.
Using original brother drivers printing works correctly.
[UnableToPrint.pdf](https://github.com/pdewacht/brlaser/files/4303209/UnableToPrint.pdf)

My printer is a brother DCP-L2500 using ubuntu 19.10 using cups 2.2.12-2ubuntu1: amd64

**Comment by al3x-huang** [comment]
did the solution in #52 fix this issue? I can print this landscape format no problem.

**Comment by reinhard66-ubuntu** [comment]
Yes, the fix helps.
Thanks
