### ISSUE TITLE
New printer DCP-T310 not works

### ISSUE THREAD

**Issue by huien126** [pdewacht/brlaser#72]
pi@raspberrypi:~ $ sudo lpinfo --include-schemes usb -l -v
Device: uri = usb://Brother/DCP-T310?serial=E78655E8H650591
        class = direct
        info = Brother DCP-T310
        make-and-model = Brother DCP-T310
        device-id = MFG:Brother;CMD:HBP,PJL;MDL:DCP-T310;CLS:PRINTER;CID:Brother Generic Jpeg Type2;
        location =

**Comment by enginvardar** [comment]
Hello @huien126 ,
have you found a solution to make DCP-T310 work? I'm trying on raspbian buster, couldn't manage to make it work yet.
it would be great if you can share the solution.

**Comment by huien126** [comment]
> Hello @huien126 ,
> have you found a solution to make DCP-T310 work? I'm trying on raspbian buster, couldn't manage to make it work yet.
> it would be great if you can share the solution.

Yes, i got it.

You can retrieve the ppd file from driver and register ppd file at CUPS.
 then it will be able to work successfully.
