### ISSUE TITLE
brlaser is not compatible with DCP-1610W.

### ISSUE THREAD

**Issue by crocket** [pdewacht/brlaser#76]
I tried to print something on DCP-1610W through brlaser.
Brlaser failed. Brother's proprietary binary driver worked.

**Comment by zeroheure** [comment]
Did you try with latest release, BrLaser 6 ?
did you try on USB ?

**Comment by crocket** [comment]
This issue was reported months after the release of BrLaser 6. I think it was tested with BrLaser 6.
I tried it on USB.

**Comment by zeroheure** [comment]
Thanks. 
Brlaser 6 is not available on all Linux distributions yet. That's why I asked.

**Comment by m0n5t3r** [comment]
it works on my machine (DCP1610W over wifi, `printer-driver-brlaser` version 6-3 from Ubuntu 22.04) - the test page says the driver is `brl600.ppd`, make and model `Brother DCP-1600 series, using brlaser v6`

**Comment by crocket** [comment]
Somehow, it works correctly now.
