### ISSUE TITLE
Heavy pdf printing issue on HL-1202

### ISSUE THREAD

**Issue by RussianNeuroMancer** [pdewacht/brlaser#80]
Hello!

I found that brlaser, even with [this commit](https://github.com/pdewacht/brlaser/commit/9d7ddda8383bfc4d205b5e1b49de2b8bcd9137f1), can't print various "heavy" pdf pages. Example of such page is page 13 of 399 in [this pdf file](https://archive.org/download/MurphyR.EnglishGrammarInUse.20124Ed._201412/Murphy%20R.%20English%20Grammar%20in%20Use.%202012%204-ed..pdf). When I trying to print this page HL-1202R just start blinking with red light.

**Comment by jamespo** [comment]
It appears that printer only has 1MB of memory, so there not be much that can be done

**Comment by RussianNeuroMancer** [comment]
> so there may not be much that can be done

It's didn't happen with vendor's driver as far I remember. Is issue reproducible for you with vendor's driver too?

**Comment by jamespo** [comment]
I have HL-1212 which has 32MB but have had these issues in the past with older printers

**Comment by RussianNeuroMancer** [comment]
Just to sure, I double checked that proprietary driver print this page just fine, despite mentioned hardware limitation. 

What you think, maybe some software workaround on driver side should be possible after all?

**Comment by RussianNeuroMancer** [comment]
Possibly related issue: https://github.com/pdewacht/brlaser/issues/40

**Comment by RussianNeuroMancer** [comment]
I tried to reduce max_lines_per_block_ to 16 and 8 on latest stable release (because of https://github.com/pdewacht/brlaser/pull/68#issuecomment-691215142 and https://github.com/pdewacht/brlaser/issues/40#issuecomment-503322537) but it didn't help on HL-1202.

@jamespo although reducing max_lines_per_block_ didn't help, I still would like to try to play around max_block_size_ and lines_per_band from https://github.com/pdewacht/brlaser/commit/9d7ddda8383bfc4d205b5e1b49de2b8bcd9137f1 but don't quite get which one of these two variables related is more related to my issue, and if I should decrease both variables at the same time or separately? Or it's unrelated to my issue at all?

Also, how I can find out how many lines_per_band is used by proprietary driver when it successfully print heavy pages to HL-1202?

**Comment by RussianNeuroMancer** [comment]
Turns out that issue was caused by the fact that I configured this printer with brlaser5 instead of brlaser6, probably because I did so long time ago (before brlaser6 release) and then forgot to re-configure it to brlaser6.

After I switched to brlaser6 manually via CUPS setting issue is no longer reproducible.
